config/routes.rb
Masterstud::Application.routes.draw do
  resources :users
  resource :session

  resources :decks do
    resources :cards, except: :index
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :front, :back, presence: true
  belongs_to :deck
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  validates :name, presence: true
  has_many :cards, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_action :find_deck
  def new
    @card = @deck.cards.new
  end

  def show
    @card = find_card
  end

  def create
    @card = @deck.cards.new(cards_params)
    if @card.save
      redirect_to @deck, notice: "Card successfully created"
    else
      render :new
    end
  end 

  def edit 
    @card = find_card
  end

  def update
    @card = find_card
    if @card.update(cards_params)
      redirect_to @deck, notice: "Card successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @card = find_card
    @card.destroy
    redirect_to @deck, notice: "Card sucessfully destroyed"
  end


  private

  def find_deck
    @deck = Deck.find(params[:deck_id])
  end

  def find_card
    @card = @deck.cards.find(params[:id])
  end

  def cards_params
    params.require(:card).permit(:front, :back)
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = Deck.all
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)
    if @deck.save
      redirect_to decks_url, notice: "Deck successfully Created"
    else
      render :new
    end
  end

  def show
    @deck = set_deck
    @cards = @deck.cards
  end

  def edit
    @deck = set_deck
  end

  def update
    @deck = set_deck
    @deck.update(deck_params)
    redirect_to @deck, notice: "Deck successfully updated"
  end

  def destroy
    @deck = set_deck
    if @deck.destroy
      redirect_to decks_url, notice: "Deck successfully destroyed"
    else
      render @deck
    end
  end
 
  private

  def deck_params
    params.require(:deck).permit(:name)
  end

  def set_deck
    @deck = Deck.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.email}!"
      redirect_to user
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to users_path, notice: "You are now signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = find_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "User successfully created"
    else
      render :new
    end
  end

  def edit
    @user = find_user
  end

  def update 
    @user = find_user
    @user.update(user_params)
    redirect_to @user, notice: "User successfully updated"
  end

  def destroy
    @user = find_user
    @user.destroy
    session[:user_id] = nil
    redirect_to users_url, notice: "User successfully deleted"
  end

private
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find_by(session[:user_id]) if session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= render 'shared/errors', object: @card %>
<%= form_for ([@deck, @card]) do |form| %>
  <div>
    <%= form.label :front %>
    <%= form.text_field :front %>
  </div>
  <div>
    <%= form.label :back %>
    <%= form.text_field :back %>
  </div>
  <%= form.submit %>
<% end %>

app/views/cards/edit.html.erb
<%=  render 'form' %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

app/views/cards/show.html.erb
<h1>The Answer is:</h1>

<%= @card.back %>

app/views/decks/_form.html.erb
<%= render 'shared/errors', object: @deck %>
<%= form_for(@deck) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing: <%= @deck.name %></h1>

<%= render 'form' %>

app/views/decks/index.html.erb
<%= link_to 'New Deck', new_deck_path %>

<h1> All Decks </h1>

<% @decks.each do |deck| %>
  <div>
    <ul><li>
      <%= link_to deck.name, deck_path(deck) %>
    </li></ul>
  </div>
<% end %>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form' %>

app/views/decks/show.html.erb
<p> <%= link_to "All Decks", decks_url %> </p> 

<h1><%= @deck.name %></h1>

<div> 
  <p> <%= link_to "Edit Deck", edit_deck_path(@deck) %> </p> 
  <p> <%= link_to "Delete", deck_path, method: :delete, confirm: "Are you sure?" %> </p>
</div>

<h2>Cards</h2>

<%= link_to "New Card", new_deck_card_path([@deck, @card]) %>

<% @cards.each do |card| %>
  <div>
    <ul><li>
    <%= link_to card.front, deck_card_path(@deck, card) %> #
    <%= link_to "Edit", edit_deck_card_path(@deck, card) %> #
    <%= link_to "Delete", deck_card_path(@deck, card), method: :delete, confirm: "Are you sure?" %>
    </li></ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav>
  <%= link_to "All Users", users_path %> |
  <% if current_user %>
    <%= link_to current_user.email, current_user %> |
    <%= link_to "Sign Out", session_path, method: :delete, confirm: "Are you sure?" %> |
  <% else %>
    <%= link_to "Sign In", new_session_path %> |
    <%= link_to "Sign Up", new_user_path %> |
  <% end %>
  <%= link_to "Decks", decks_path %> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Masterstud</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <p class="flash">
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>
  </p>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <% object.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
    <% end %>
  <% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>

<ul>
  <%= form_for(@user) do |form| %>
    <li><%= form.label :email%>
    <%= form.text_field :email %></li>

    <li><%= form.label :password%>
    <%= form.password_field :password%></li>

    <li><%= form.label :password_confirmation, "Confirm Password"%>
    <%= form.password_field :password_confirmation %></li>
    
    <%= form.submit %>
  <% end %>
</ul>

app/views/users/edit.html.erb
<h1>Editing User:</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users: </h1>

<h2>
  <ul>
    <% @users.each do |user| %>
    <li><%= link_to user.email, user %></li> 
    <% end %>
  </ul>
<h2>

app/views/users/new.html.erb
<h1>Create User:</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<div> 
  <p> <%= link_to "Edit User", edit_user_path(@user) %> </p> 
  <p> <%= link_to "Delete User", user_path, method: :delete, confirm: "Are you sure?" %> </p>
</div>